// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Pd1nPG2SrtaaL-NfLyPLkglep1Ckdhg',
    appId: '1:240245495483:android:a4fba1cc293328aa197b9e',
    messagingSenderId: '240245495483',
    projectId: 'bid-parl',
    storageBucket: 'bid-parl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwqRARohPaYgKYBtt3rce3H6r-REIYF1Q',
    appId: '1:240245495483:ios:a388fbeae0681edc197b9e',
    messagingSenderId: '240245495483',
    projectId: 'bid-parl',
    storageBucket: 'bid-parl.appspot.com',
    androidClientId: '240245495483-ovu7i9fdnlobl7vkhqissm5u25gd3ti1.apps.googleusercontent.com',
    iosClientId: '240245495483-ebroa3tn63qmsmo8j523pd96ngpa4ohh.apps.googleusercontent.com',
    iosBundleId: 'bid.cryptoTemplate',
  );
}
